version: '3.8'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: watch      # Tên database
      POSTGRES_USER: postgres  # Username
      POSTGRES_PASSWORD: 1    # Password
    ports:
      - "5432:5432"          # Port mặc định
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/watch
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
      # Nếu cần cấu hình OAuth2 / mail / JWT, có thể thêm ENV tương tự:
      # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID: <your-client-id>
      # SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: <your-secret>
      # JWT_SECRET: ThayBanBangChuoiBiMatRiengCuaBan
      # JWT_EXPIRATION_MS: 86400
    depends_on:
      - db

volumes:
  db-data: